services:
  rpc_health_checker:
    build: .
    container_name: health
    restart: always
    command:
      - '--log-level INFO'
    ports:
      - "53336:53336"
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
