services:
  rpc_health_checker:
    build: .
    container_name: health
    restart: unless-stopped
    ports:
      - "53336:53336"
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
